# Generated by Django 4.1.4 on 2023-01-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0002_news_date_alter_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cosmos/static/images')),
            ],
        ),
    ]
